#include <iostream>
#include <memory>
#include "Valu.h"               // Generated by Verilator from alu.v
#include "verilated.h"
#include "verilated_vcd_c.h"    // Required for waveform dumping

int main(int argc, char** argv) {
    // Initialize Verilator context and arguments
    Verilated::commandArgs(argc, argv);
    auto contextp = std::make_unique<VerilatedContext>();
    
    // Instantiate our ALU module
    auto top = std::make_unique<Valu>(contextp.get());

    // Set up waveform dumping
    Verilated::traceEverOn(true);
    auto tfp = std::make_unique<VerilatedVcdC>();
    top->trace(tfp.get(), 99); // Trace 99 levels of hierarchy
    tfp->open("wave.vcd");     // Name of the output waveform file

    int sim_time = 0;

    // Test Case 1: ADD (op = 00) -> 5 + 3 = 8
    top->a = 5; top->b = 3; top->op = 0;
    top->eval();               // Evaluate the circuit
    tfp->dump(sim_time++);     // Dump variables into the VCD
    
    // Test Case 2: SUB (op = 01) -> 10 - 4 = 6
    top->a = 10; top->b = 4; top->op = 1;
    top->eval();
    tfp->dump(sim_time++);

    // Test Case 3: AND (op = 10) -> 0xF & 0x3 = 0x3
    top->a = 0xF; top->b = 0x3; top->op = 2;
    top->eval();
    tfp->dump(sim_time++);

    // Test Case 4: OR (op = 11) -> 0x4 | 0x2 = 0x6
    top->a = 0x4; top->b = 0x2; top->op = 3;
    top->eval();
    tfp->dump(sim_time++);

    // Clean up and close the trace file
    tfp->close();
    std::cout << "Simulation complete! wave.vcd generated." << std::endl;
    return 0;
}